### ISSUE TITLE
JCA Client Id seed data make Jans CLI fail

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-config-api#6] opened 2021-01-04 21:49 UTC
When in Cloud Native version, the JCA Client Id created in config-api makes Jans CLI fail because "clientName" is not set and it's a required attribute in Config API schema.

This issue is related with https://github.com/JanssenProject/jans-cli/issues/2

**Comment by ruiengana** [comment] 2021-01-23 22:10
@nynymike ,can you help with this issue?

**Comment by mbaser** [comment] 2021-01-25 08:54
I updated yaml file, and swagger. `clientName` is tagged as **required** in latest yaml. So the issue is resolved.

https://github.com/JanssenProject/jans-cli/blob/main/jca.yaml#L3730-L3735

@ruiengana , please check jca-client and close this issue if resolved.

**Comment by ruiengana** [comment] 2021-01-25 09:05
@mbaser the problem is on the seed Config API client created during install, that client is created directly in persistence and doesn't have clientName, which cause a whole load of problems in CLI and API since they are expecting it.

**Comment by mbaser** [comment] 2021-01-25 18:57
I checked all is good.

**Comment by mbaser** [comment] 2021-01-25 18:59
@ruiengana Can you install latest Jans? May be we fixed the issue after you installed.

**Comment by ruiengana** [comment] 2021-01-25 19:01
> @ruiengana Can you install latest Jans? May be we fixed the issue after you installed.
@mbaser , please note this happens using Jans Cloud Native version.

**Comment by mbaser** [comment] 2021-01-26 16:44
I will test once I got  a cloud installation. Most probably the issue was fixed with this commit https://github.com/JanssenProject/jans-setup/commit/228f0b6f79ab48c7f7f79577026c01bb1632c263

**Comment by iromli** [comment] 2021-01-26 17:31
In Cloud Native, the addition of `displayName` to Config API client is at https://github.com/JanssenProject/docker-jans-persistence-loader/commit/d4f33b95bf136fbdcc1674f12f06b090f2e4ce91. However, this changeset is available in `janssenproject/persistence-loader:1.0.0_dev`

**Comment by moabu** [comment] 2021-01-26 18:18
@ruiengana you can confirm that the issue has been resolved but you must use images with tag `1.0.0_dev` . We will release the next alpha version to include this as soon as we close in on the scim issue.

**Comment by ruiengana** [comment] 2021-02-11 23:16
@moabu , confirmed today that dev images have this fix included.

**Closed** 2021-02-12 16:01 UTC
